In [ ]:
## Numpy
- 선형대수, 행렬 수치연산과 관련된 라이브러리

In [ ]:
import numpy as np

print(np.__version__)

In [ ]:
num1=[1,2,3,4]
num2=[3,4,5,6]

num1+num2

In [ ]:
arr1=np.array(num1)
arr2=np.array(num2)

In [ ]:
arr1

In [ ]:
arr2

In [ ]:
arr1+arr2

In [ ]:
data1=[0,1,2,3,4,5]
a1=np.array(data1)
a1

In [ ]:
a1.dtype

In [ ]:
np.array([0.5,2,0.01,8]).dtype

In [ ]:
# Numpy 배열 생성
- 1차원, 2차원, 3차원.. 배열 생성

In [ ]:
np.arange(0,10,2)

In [ ]:
np.arange(1,10)

In [ ]:
np.arange(10)

In [ ]:
np.arange(12).reshape(4,3) #==>reshape 메서드는 reshape(a,b) a행, b열 로 행렬의 형태로 만들어준다.

In [ ]:
b1=np.arange(12).reshape(4,3)
b1.shape

In [ ]:
b2=np.arange(5)
b2.shape

In [ ]:
# 범위의 시작과 끝 정하기 배열 생성 linspace(a,b,c) a와 b사이에서 c개 만큼 배열을 만들어달라는 메서드
np.linspace(0, 10, 5)

In [ ]:
np.linspace(0, np.pi,20)

In [ ]:
np.zeros(10)

In [ ]:
np.zeros((2,2))

In [ ]:
np.ones(10)

In [ ]:
np.ones((2,2))

In [ ]:
# 단위 행령 만들기
arr_I=np.eye(3)
arr_I

In [ ]:
arr_I.shape

In [ ]:
np.array(['1.5','0.62'])

In [ ]:
# astype() #pandas에서 사용가능
arr=np.array(['1.5','0.62'])
num_arr=arr.astype(float)
num_arr.dtype

In [ ]:
num_f1=np.array([10,21,0.549,4.75,5.98])
num_i1=num_f1.astype(int)
num_i1

In [ ]:
num_f2=np.array([10,21,0.549,4.75,5.98])
num_i2=num_f2.astype(float)
num_i2

In [ ]:
# 난수 무작위로 숫자를 추출한다. random모듈을 사용해서 rand(),randin()를 사용해서 무작위로 숫자를 뽑는다. 

In [ ]:
np.random.rand(2,3) # ==> 난수를 뽑아 2*3행렬로 만들어준다. ==>파이썬에서 random과 같이 rand()는 0과1사이에서 기본적으로 난수를 뽑아준다.

In [ ]:
np.random.randint(10,size=(3,4)) # ==> 정수 10아래에서 3*4행렬의 사이즈로 난수로 행렬을 만들어준다. randint(a,b,size)는 a와b 사이에 정수를 size에 들어온 행렬의 크기만큼 난수로 뽑아준다.

In [ ]:
np.random.randint(1,100,10)

In [ ]:
np.random.randint(46,size=6)

In [ ]:
# 로또 6자리 숫자를 랜덤으로 뽑는 알고리즘
result_s=set()
while len(result_s)<6:
    number=random.randint(1,47)
    result_s.add(number)
    #print(result)
print(result_s)
    

In [ ]:
number=random.randint(1,47)
print(number)

In [ ]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])

print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

In [ ]:
#비교연산

In [ ]:
arr1>20

In [ ]:
## 통계 연산
- Numpy , 합, 평균, 표준편차, 분산, 최솟값, 최댓값, 누적합,누적 곱 메서드가 존재한다.
  + 기술통계량 (Descriptive Statistics) : 현재 데이터 상태를 표현(=묘사 , Desdcribe)한다.
- 통계 : 평균이 전부다!!!
  +모수 통계
  +비모수 통계
  +베이지안 통계

In [250]:
arr3=np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [253]:
arr3.sum()

10

In [254]:
arr3.mean()

2.0

In [255]:
arr3.std() # 표준편차(standard deviation)는 분산을 제곱근한 것이다. 제곱해서 값이 뻥튀기 된 분산을 제곱근해서 다시 원래 크기로 만들어준다.

1.4142135623730951

In [256]:
arr3.var() # 분산(variance)은 관측값에서 평균을 뺀 값을 제곱하고, 그것을 모두 더한 후 전체 수로 나눠서 구한다. 즉, 차이값의 제곱의 평균이다. 
           # 관측값에서 평균을 뺀 값인 편차를 모두 더하면 0이 나오므로 편차의 부호를 없애기 위해 제곱해서 더한다. 또한 분산은 표준편차의 제곱이다.

2.0

In [ ]:
## 누적합과 누적곱
 - cumsum() : 누적합
 - cumprod() : 누적곱

In [257]:
arr4 = np.arange(1,5)
arr4

array([1, 2, 3, 4])

In [259]:
arr4.cumsum() # 누적합

array([ 1,  3,  6, 10])

In [260]:
arr4.cumprod() # 누적곱

array([ 1,  2,  6, 24])

In [ ]:
## 행렬연산
 - 선형 대수(Linear Algebra)를 위한 2차원 배열 연산도 지원

In [261]:
A = np.array([0,1,2,3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [262]:
B = np.array([3,2,1,0]).reshape(2,2)
B

array([[3, 2],
       [1, 0]])

In [263]:
A.dot(B) # ==> 행렬의 내적

array([[1, 0],
       [9, 4]])

In [264]:
np.dot(A,B) # ==> 행렬의 내적

array([[1, 0],
       [9, 4]])

In [265]:
A.transpose() # ==> 전치행렬 구하는법(행과 열을 바꾸는 행렬이 전치행렬이다.)

array([[0, 2],
       [1, 3]])

In [267]:
np.linalg.inv(A) # ==> 역행렬을 구하는법

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [ ]:
## 배열의 인덱싱과 슬라이싱
 - string,list,tuple과 동일한 방법으로 접근

In [275]:
a1=np.array([0,10,20,30,40,50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [270]:
a1[5] # ==> 파이썬의 인덱싱방법과 비슷하다.

50

In [271]:
a1[5]=60
a1

array([ 0, 10, 20, 30, 40, 60])

In [276]:
# 리스트를 통해서 추출 인덱싱하는 방법에서 안에 또 리스트를 넣어서 리스트로 결과값을 뽑아냈다.
a1[[0,2,4]]

array([ 0, 20, 40])

In [277]:
a2=np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [279]:
a2[2,2]

90

In [281]:
# 90을 95로 변경
a2[2,2]=95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [282]:
a2[0]

array([10, 20, 30])

In [284]:
a2[0]=[1,2,3] # ==> 조금 유연한 파이썬의 문법구조에 의해서 가능한것
a2

array([[ 1,  2,  3],
       [40, 50, 60],
       [70, 80, 95]])

In [285]:
a2[0]=np.array([4,5,6]) # ==> 이것이 정석이다.
a2

array([[ 4,  5,  6],
       [40, 50, 60],
       [70, 80, 95]])

In [286]:
a2[0]=np.array([4,5,6,7]) # ==> a2의 0번째 행에는 열이 3개인데 4개의 열을 추가하려고 하니까 오류가 떳다.
a2

ValueError: could not broadcast input array from shape (4,) into shape (3,)

In [ ]:
- 2차원 배열의 행과 열 위치 지정해서 원소 추출

In [287]:
a2

array([[ 4,  5,  6],
       [40, 50, 60],
       [70, 80, 95]])

In [288]:
a2[[0,2],[0,1]] # ==> 잘생각해보기 바로 밑에 코드를 보고 이것은 배열이기 때문에 그렇다는데 잘 이해가 안됨

array([ 4, 80])

In [291]:
a2[0,0] , a2[2,1] # ==> 이걸보고 위에거를 잘생각해보기

(4, 80)

In [292]:
a2[[0,1],[1,2]] # ==> 바로밑에 코드와 같은 것이다.

array([ 5, 60])

In [293]:
a2[0,1] , a2[1,2]

(5, 60)

In [289]:
a2[0,2] , a2[0,1]

(6, 5)

In [ ]:
## 배열 조건문
  -pandas의 문법과 유사하다.

In [294]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [295]:
a[a>3]

array([4, 5, 6])

In [296]:
a>3

array([False, False, False,  True,  True,  True])

In [297]:
a % 2 ==0

array([False,  True, False,  True, False,  True])

In [ ]:
## 배열의 슬라이싱

In [298]:
b1=np.array([0,10,20,30,40,50])
b1[1:4]

array([10, 20, 30])

In [299]:
b1[:3]

array([ 0, 10, 20])

In [300]:
b1[1:]

array([10, 20, 30, 40, 50])

In [301]:
b1[::2]

array([ 0, 20, 40])

In [302]:
b1[2:5]=np.array([25,35,45])
b1

array([ 0, 10, 25, 35, 45, 50])

In [303]:
b1[3:6]=60
b1

array([ 0, 10, 25, 60, 60, 60])

In [305]:
b2=np.arange(10,100,10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [306]:
b2[1:3 , 1:3] # ==> b2[행_시작_위치:행_끝_위치 , 열_시작_위치,열_끝_위치]에 해당하는 경우이다.

array([[50, 60],
       [80, 90]])

In [307]:
b2[1:, 1:]

array([[50, 60],
       [80, 90]])

In [308]:
b2[1]

array([40, 50, 60])

In [312]:
b2[1][1:3]

array([50, 60])

In [ ]:
## NumPy 조건문
 - np.where : 단일 조건문
 - np.select : 다중 조건문

In [313]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [318]:
# 0, 1, 2, 3, 4, 50, 60, 70, 80, 90
np.where(arr>5 , arr*10, arr)

array([ 0,  1,  2,  3,  4,  5, 60, 70, 80, 90])

In [ ]:
# 0, 1, 2, 3, 4, 50, 60, 70, 80, 90
np.where(arr<5 , arr, arr*10)

In [321]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [326]:
# 100, 101, 2,,3, 4, 5, 12, 14, 16, 18
# 2 미만 일 때는 100을 더해라
# 5 초과 일 때는 곱하기 2를 해줘라

#조건식과 대응되는 결과를 리스트로 만들기
cond_list = [arr>5, arr<2]
choice_list = [arr*2, arr+100]
np.select(cond_list, choice_list, arr)

array([100, 101,   2,   3,   4,   5,  12,  14,  16,  18])